package edu.berkeley.cs.amplab

import java.io.File
import java.io.PrintWriter

object MkLauncher {
  def main(args: Array[String]) {
    val out = new PrintWriter("spark-home/set-classpath.sh")
    out.println("""# This file is automatically generated.""")
    out.println("CLASSPATH=" + System.getProperty("java.class.path"))
    out.println("JAVA_LIBRARY_PATH=" + System.getProperty("java.library.path"))
    out.println("BOOT_CLASSPATH=" + System.getProperty("sun.boot.class.path"))
    out.println("export CLASSPATH JAVA_LIBRARY_PATH BOOT_CLASSSPATH")
    out.close
  }
}
